name: CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push image 
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile  
          push: true
          tags: lavalex/snake-game:${{ github.sha }}

      - name: Update GitOps Repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          
          # Clone the gitops repo
          git clone https://x-access-token:${{ secrets.GIT_ACCESS_TOKEN }}@github.com/lavalex/snake-gitops.git
          cd snake-gitops
         
          # Use a more flexible regex that matches everything after 'image: '
          sed -i "s|image: .*|image: docker.io/lavalex/snake-game:${{ github.sha }}|g" deployment-game.yaml
          
          # Only commit if there are changes
          if [[ -n $(git status -s) ]]; then
            git add deployment-game.yaml
            git commit -m "Update image tag to ${{ github.sha }}"
            git push
          else
            echo "No changes to commit."
          fi

       - name: Purge old images
         uses: chialab/docker-hub-tag-limiter@main
         with:
           username: ${{ secrets.DOCKER_USERNAME }}
           password: ${{ secrets.DOCKER_PASSWORD }}
           repository: lavalex/snake-game
           tags-to-keep: 3   

